version: '2'
services:
  api:
    build: api/.
    command: yarn run start-dev
    depends_on:
      - mongo
    environment:
      JWT_SECRET: secret
      NODE_ENV: development
      DB_URI: mongodb://mongo:27017/generators
    ports:
      - '3000:3000'
    volumes:
      - ./api/.:/opt/app
      - /opt/app/node_modules
  mongo:
    image: mongo:3.0.7
    ports:
      - "27017:27017"
